//! Differential test: assert our encoder matches the Python `sentencepiece`
//! oracle token-for-token, across both a BPE and a Unigram model.
//!
//! Oracle files are generated by `oracle/gen_oracle.py` (see README.md). Until
//! they exist the test is skipped with a message rather than failing, so
//! `cargo test` is green on a fresh checkout.

use std::path::Path;

use sentencepiece_rs::SentencePieceProcessor;

/// (model fixture, generated oracle cases) pairs.
const SUITES: &[(&str, &str)] = &[
    ("tests/models/botchan_1000_bpe.model", "oracle/cases.tsv"),
    (
        "tests/models/test_oss_model_unigram.model",
        "oracle/cases_unigram.tsv",
    ),
    (
        "tests/models/wagahaiwa_2000_bpe_byte.model",
        "oracle/cases_byte.tsv",
    ),
];

fn hex_decode(s: &str) -> Vec<u8> {
    let b = s.as_bytes();
    (0..b.len() / 2)
        .map(|i| {
            let hi = (b[2 * i] as char).to_digit(16).unwrap();
            let lo = (b[2 * i + 1] as char).to_digit(16).unwrap();
            (hi * 16 + lo) as u8
        })
        .collect()
}

#[derive(Default)]
struct Stats {
    checked: usize,
    /// Encode differed but is a same-multiset reordering — an equally-optimal
    /// Viterbi segmentation (identical total score). Accepted; see the precision
    /// fence in `src/unigram.rs`.
    score_ties: usize,
    /// Encode differed in the *set* of pieces — a genuine bug.
    real_mismatches: usize,
}

fn sorted(v: &[i32]) -> Vec<i32> {
    let mut v = v.to_vec();
    v.sort_unstable();
    v
}

fn verify(model: &str, cases: &str, stats: &mut Stats) {
    let sp = SentencePieceProcessor::open(model).expect("load model");
    let data = std::fs::read_to_string(cases).expect("read cases");

    for (lineno, line) in data.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() {
            continue;
        }
        let mut cols = line.split('\t');
        let hex_text = cols.next().expect("missing text column");
        let ids_str = cols.next().expect("missing ids column");
        let hex_decoded = cols.next().expect("missing decoded column");

        let text = String::from_utf8(hex_decode(hex_text)).expect("utf8 text");
        let expected: Vec<i32> = ids_str
            .split_whitespace()
            .map(|t| t.parse().unwrap())
            .collect();
        let expected_decoded = String::from_utf8(hex_decode(hex_decoded)).expect("utf8 decoded");

        // encode: text -> ids
        let got = sp.encode(&text).expect("encode");
        if got != expected {
            if sorted(&got) == sorted(&expected) {
                // Equal-score tie: same pieces, different order. Acceptable.
                stats.score_ties += 1;
                if stats.score_ties <= 3 {
                    eprintln!("[{model}] L{} score-tie reorder: {:?}", lineno + 1, text);
                }
            } else {
                stats.real_mismatches += 1;
                if stats.real_mismatches <= 8 {
                    eprintln!(
                        "[{model}] REAL encode mismatch L{}: {:?}\n  got: {:?}\n  exp: {:?}",
                        lineno + 1,
                        text,
                        got,
                        expected
                    );
                }
            }
        }

        // decode: ids -> text (oracle ids -> our text == oracle text)
        let got_decoded = sp.decode(&expected).expect("decode");
        assert_eq!(
            got_decoded,
            expected_decoded,
            "[{model}] decode mismatch on line {} for ids {:?}",
            lineno + 1,
            expected
        );
        stats.checked += 1;
    }
}

#[test]
fn matches_python_oracle() {
    let missing: Vec<&str> = SUITES
        .iter()
        .filter(|(_, cases)| !Path::new(cases).exists())
        .map(|(_, cases)| *cases)
        .collect();
    if !missing.is_empty() {
        eprintln!(
            "skipping: missing oracle file(s) {missing:?}. \
             Generate them by running oracle/gen_oracle.py for each fixture over \
             corpus_ascii.txt (>) then corpus_unicode.txt (>>); see README.md for \
             the exact commands (cases.tsv, cases_unigram.tsv, cases_byte.tsv)."
        );
        return;
    }

    let mut stats = Stats::default();
    for (model, cases) in SUITES {
        verify(model, cases, &mut stats);
    }
    eprintln!(
        "checked {} cases against the Python oracle: {} exact, {} equal-score reorderings, {} real mismatches",
        stats.checked,
        stats.checked - stats.score_ties - stats.real_mismatches,
        stats.score_ties,
        stats.real_mismatches
    );
    assert!(stats.checked > 0, "oracle files contained no cases");
    assert_eq!(
        stats.real_mismatches, 0,
        "{} genuine (different-piece) encode mismatches (see above)",
        stats.real_mismatches
    );
}
